### ISSUE TITLE
You might also like section is missing from Cart page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Yakir-Internal-Group-21st-Jan-2022#1]
You might also like section is missing from preview.
**Steps** 
Add any product to the cart & go to cart page.
Preview link: https://sd1m6so1adkbguvz-50734989498.shopifypreview.com/cart 
Live link: https://www.wholedent.com/cart 
Preview SS: 
![image](https://user-images.githubusercontent.com/97726944/162665566-db286dab-0efa-4035-914a-20d9caba6477.png)
Live SS: 
![image](https://user-images.githubusercontent.com/97726944/162665590-ea75a3af-d165-41b5-b552-5f5a0a33d0ae.png)

**Comment by devRitikTamrakar** [comment]
![image](https://user-images.githubusercontent.com/100219171/162683486-b35a13a2-dc1b-4e56-b3dc-37ef9b385071.png)
it's working fine once I publish this theme. we can recheck it after making it live.
